- name: copy mysql 5.7 repo to mysql server repository location
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disabling Mysql Module
  ansible.builtin.command:
    cmd: dnf module disable mysql -y

- name: Install Mysql-Community 5.7
  ansible.builtin.dnf:
    name: mysql-community-server
    state: present

- name: Enable and start the mysql service
  ansible.builtin.systemd_service:
    enabled: true
    name: mysqld
    state: started  

- name: Changing the default root password in order to start using the database service
  ansible.builtin.command:
    cmd: mysql_secure_installation --set-root-pass RoboShop@1