- name: "{{component}} app setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: "{{component}} golang setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: golang

- name: "copy {{component}} service to systemd path"
  ansible.builtin.copy:
    src: dispatch.service
    dest: /etc/systemd/system/dispatch.service

- name: "Daemon reload to update {{component}} service and restart"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd