- name: Install Nginx WebServer
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Delete a html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download a web application to host on nginx
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp/

- name: Unrachive or Extract the web application to the below location
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy Nginx Reverse Proxy Configuration file from Ansible Tower to Nginx server
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start and Enable the Nginx service
  ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes