- name: "Disabling NodeJS version in {{component}}"
  ansible.builtin.command:
    cmd: dnf module disable nodejs -y

- name: "Enabling NodeJS 18 version in {{component}}"
  ansible.builtin.command:
    cmd: dnf module enable nodejs:18 -y

- name: "Installing NodeJS in {{component}}"
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: "Installing {{component}} application"
  ansible.builtin.command:
    cmd: npm install
  args:
    chdir: /app