   - name: Install Python 3.6
     ansible.builtin.dnf:
        name: "{{item}}"
        state: present
      loop:
        - python36
        - gcc
        - python3-devel

   - name: Download the dependices
     ansible.builtin.command:
       cmd: pip3.6 install -r requirements.txt
     args:
       chdir: /app